server:
  port: 8096

spring:
  datasource:
    url: jdbc:mysql://mydbtest.crlh79gbx3lq.us-east-1.rds.amazonaws.com:3306/myDBTest
    username: root
    password: Mukul2105

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

jwt:
  secret: z%C*F-JaNdRgUkXp2s5u8x/A?D(G+KbPeShVmYq3t6w9y$B&E)H@McQfTjWnZr4u
  expiry: 10