package in.mpApp.JwtWithAWS.enums;

public enum BookCategory {

    CLASSIC, ACTION_AND_ADVENTURE, COMIC, DETECTIVE, FANTASY, HISTORICAL, HORROR, FICTION, ROMANCE, SCIENCE, SHORT_STORIE, SUSPENSE_AND_THRILLER,
    BIOGRAPHY, COOKBOOK, ESSAY, MEMOIR, POETRY, SELF_HELP,

}
